language: python
python: 3.7

install:
- pip install -r requirements.txt

before_script:
  - pylint --version
  - pytest --version

script:
- pytest --disable-warnings --cov=src/
- pylint src/preprocess.py